### PR TITLE
Added a11y to menu

### PR DESCRIPTION
**Pull request by brianburrier**
Client with accessibility background requested adding aria-current="page" to the link in the navigation as well as the parent category.

1. Added function that finds the ending path name (e.g. /wills-and-living-trusts)
2. var currPage stores the current page's URL path name
3. Script loops through all the links in the nav and if the path name matches what's stored in currPage, it sets the attribute aria-current="page" to that link
4. Script then loops through the top categories, and if it's children has a path name that matches currPage, it also sets the attribute on the parent category (e.g. Easy Gifts)

**Review here:** https://stelterstaging.ingeniuxondemand.com/sds-dev-brian/wills-and-living-trusts

### CODE REVIEW

**Comment by joshsummers** [comment]
Is the second loop to set the attribute on the nav category necessary? I tested just setting the attribute on both the current page's link and it's parent nav group link in the same loop at that seemed to work.

`// Check nav links for href value, if it's the current page set attribute
$('#rightnav a').each(function () {            
    if ( $(this).attr('href') !== undefined) {
        var hrefVal = $(this).attr('href');	
        hrefVal = getUrlPath(hrefVal);
    
        if (hrefVal == currPage) {
            $(this).attr('aria-current', 'page');
            $(this).parent().parent().siblings().attr('aria-current', 'page');
        }
    }
});
// set the attribute if a subnav link is the current page
/*
$('#rightnav > li.onTrail > a').each(function () {
	var currChild = false;

    $(this).next('ul').children().children('a').each(function() {            	
        var childHref = $(this).attr('href');
        childHref = getUrlPath(childHref);

	    if (childHref == currPage) {
	        $(this).parent().parent().siblings().attr('aria-current', 'page')
	    }
	            	           
    });
});
*/`

**Comment by joshsummers** [comment]
Is the second loop to set the attribute on the nav category necessary? I tested just setting the attribute on both the current page's link and it's parent nav group link in the same loop at that seemed to work.

`// Check nav links for href value, if it's the current page set attribute
$('#rightnav a').each(function () {            
    if ( $(this).attr('href') !== undefined) {
        var hrefVal = $(this).attr('href');	
        hrefVal = getUrlPath(hrefVal);
    
        if (hrefVal == currPage) {
            $(this).attr('aria-current', 'page');
            $(this).parent().parent().siblings().attr('aria-current', 'page');
        }
    }
});`

**Comment by brianburrier** [comment]
Are you referring to the loop that assigns the aria label to the parent category? Without it the parent category wouldn't get the label. Which part did you remove that had it still working on both the sub nav and category?

It does look like line 89 can be removed though 
`var currChild = false;`

**Comment by joshsummers** [comment]
The only loop that I currently have is the first one and it works. It adds the aria-current to both the current page link and the current page's parent link. You're already looping through all of the links and checking to see if it's the current page in the first loop, so you should be able to to just set the attribute on the current page and the current page's parent both in that same loop rather than looping through the all the links and checking for the current page again just to set the attribute on the parent. The code in my first comment is what I have working, it just didn't format it very well. Basically all I did was I moved this line $(this).parent().parent().siblings().attr('aria-current', 'page');  into the first loop and commented out the second one loop completely.  https://www.screencast.com/t/ceZBxexE23U

**Comment by brianburrier** [comment]
@joshsummers  I see what you're saying now. I've updated the code in the last commit, "changes from suggestions".

**Review by joshsummers — APPROVED** [review]

**Pull request merged**
